services:
  app:
    container_name: irodori-tts-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IRODORI_TTS_BACKEND: ${IRODORI_TTS_BACKEND:-cu128}
    ports:
      - "8088:8088"
    volumes:
      - ./hf_cache:/root/.cache/huggingface
      - ./voices:/voices
    environment:
      - IRODORI_HF_CHECKPOINT=Aratako/Irodori-TTS-v4.1-Small-MF
      - IRODORI_MODEL_DEVICE=cuda
      - IRODORI_MODEL_PRECISION=bf16
      - IRODORI_CODEC_PRECISION=bf16
      - IRODORI_PRELOAD=true
      - IRODORI_VOICES_DIR=/voices
    command: ["/app/.venv/bin/python", "-m", "irodori_openai_tts"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              # count: all
              capabilities: [gpu]
    # restart: unless-stopped

